background {
    #monitor =
    path = screenshot
    blur_passes = 2
}

input-field {
    #monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    fade_on_empty = false
    placeholder_text = "@Pass$word@"
}
