source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/my_programs.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/env_vars.conf
source = ~/.config/hypr/conf/look_and_feel.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/windows_and_workspaces.conf
