# See https://wiki.hypr.land/Configuring/Basics/Monitors/
# monitor = port_name, resolution, position, scale
monitor=HDMI-A-5, 1920x1080, 0x0, 1 # Left
monitor=DP-3, 1920x1080, 1920x0, 1  # Middle
monitor=DP-5, 1920x1080, 3840x0, 1  # Right
